name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # or 3.13 if compatible

      - name: Upgrade pip
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: pip install -r windows-build-requirements.txt

      - name: Build executable
        run: pyinstaller --onefile --noconsole app.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-windows-exe
          path: dist/*.exe
