name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller
          pip freeze > pip-freeze.txt

      - name: Build EXE
        run: |
          pyinstaller --clean EvidenceSynthesis.spec
          if (Test-Path dist) { dir dist -Recurse }

      - name: Smoke run (headless) + health check
        shell: pwsh
        env:
          STREAMLIT_SERVER_HEADLESS: "true"
          STREAMLIT_BROWSER_GATHER_USAGE_STATS: "false"
          STREAMLIT_SERVER_PORT: "8501"
          STREAMLIT_SERVER_ADDRESS: "127.0.0.1"
        run: |
          $exe = Join-Path "dist" "EvidenceSynthesisApp" "EvidenceSynthesisApp.exe"
          Write-Host "Starting $exe ..."
          Start-Process -FilePath $exe
          $deadline = (Get-Date).AddMinutes(2)
          $ok = $false
          while ((Get-Date) -lt $deadline) {
            try {
              $r = Invoke-WebRequest -Uri "http://127.0.0.1:8501/healthz" -UseBasicParsing -TimeoutSec 5
              if ($r.StatusCode -eq 200) { $ok = $true; break }
            } catch {
              Start-Sleep -Seconds 2
            }
          }
          if (-not $ok) {
            Write-Error "App did not become healthy on /healthz"
            exit 1
          }

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: |
            dist/**
            pip-freeze.txt
            **/streamlit*.log
          if-no-files-found: warn
