name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'    # 3.13 also works with the pins above

      - name: Upgrade pip
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: pip install -r windows-build-requirements.txt

      # ---------- 1️⃣ Diagnostic build (folder, with console) ----------
      - name: Build (diagnostic onedir + console)
        run: >
          pyinstaller --clean --onedir --console
          --name EvidenceSynthesisApp
          --collect-all streamlit
          --collect-all pandas
          --collect-all numpy
          --collect-all pyarrow
          --hidden-import sklearn.utils._cython_blas
          --hidden-import sklearn.utils._openmp_helpers
          app.py

      # (optional) quick test that diagnostic build runs
      - name: Smoke test diagnostic (onedir)
        shell: pwsh
        run: |
          $exe = "dist\EvidenceSynthesisApp\EvidenceSynthesisApp.exe"
          $p = Start-Process -FilePath $exe -ArgumentList "--server.headless true --server.port 8502 --browser.gatherUsageStats false" -PassThru
          $ok = $false
          for ($i=0; $i -lt 30; $i++) {
            Start-Sleep -Seconds 1
            try {
              $resp = Invoke-WebRequest -Uri "http://127.0.0.1:8502/" -UseBasicParsing -TimeoutSec 2
              if ($resp.StatusCode -eq 200) { $ok = $true; break }
            } catch { }
          }
          if (-not $ok) {
            Write-Host "❌ Diagnostic app didn’t respond on port 8502"
            if ($p -and -not $p.HasExited) { Stop-Process -Id $p.Id -Force }
            exit 1
          }
          Write-Host "✅ Diagnostic app responded on port 8502"
          if ($p -and -not $p.HasExited) { Stop-Process -Id $p.Id -Force }

      - name: Zip diagnostic app folder
        shell: pwsh
        run: |
          Compress-Archive -Path dist\EvidenceSynthesisApp\* -DestinationPath EvidenceSynthesisApp_onedir.zip -Force
          Get-ChildItem EvidenceSynthesisApp_onedir.zip | Select-Object Name, Length

      - name: Upload artifact (diagnostic)
        uses: actions/upload-artifact@v4
        with:
          name: EvidenceSynthesisApp_onedir
          path: EvidenceSynthesisApp_onedir.zip
          if-no-files-found: error
          retention-days: 7

      # ---------- 2️⃣ Release build (single .exe, no console) ----------
      - name: Build (release onefile + no console)
        run: >
          pyinstaller --clean --onefile --noconsole
          --name EvidenceSynthesisApp
          --collect-all streamlit
          --collect-all pandas
          --collect-all numpy
          --collect-all pyarrow
          --hidden-import sklearn.utils._cython_blas
          --hidden-import sklearn.utils._openmp_helpers
          app.py

      # ✅ Smoke test release .exe before packaging
      - name: Smoke test .exe (start, ping, stop)
        shell: pwsh
        run: |
          $exe = Join-Path "dist" "EvidenceSynthesisApp.exe"
          $p = Start-Process -FilePath $exe -ArgumentList "--server.headless true --server.port 8501 --browser.gatherUsageStats false" -PassThru

          $ok = $false
          for ($i=0; $i -lt 30; $i++) {
            Start-Sleep -Seconds 1
            try {
              $resp = Invoke-WebRequest -Uri "http://127.0.0.1:8501/" -UseBasicParsing -TimeoutSec 2
              if ($resp.StatusCode -eq 200) { $ok = $true; break }
            } catch { }
          }

          if (-not $ok) {
            Write-Host "❌ App did not respond on http://127.0.0.1:8501/"
            if ($p -and -not $p.HasExited) { Stop-Process -Id $p.Id -Force }
            exit 1
          }

          Write-Host "✅ App responded on http://127.0.0.1:8501/"
          if ($p -and -not $p.HasExited) { Stop-Process -Id $p.Id -Force }

      - name: Zip release exe
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path upload | Out-Null
          Copy-Item dist\*.exe upload\ -ErrorAction SilentlyContinue
          Copy-Item dist\**\*.exe upload\ -ErrorAction SilentlyContinue
          Compress-Archive -Path upload\* -DestinationPath EvidenceSynthesisApp.zip -Force
          Get-ChildItem EvidenceSynthesisApp.zip | Select-Object Name, Length

      - name: Upload artifact (release)
        uses: actions/upload-artifact@v4
        with:
          name: EvidenceSynthesisApp
          path: EvidenceSynthesisApp.zip
          if-no-files-found: error
          retention-days: 7
