name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip setuptools wheel

      # Install dependencies (use a file if present; otherwise minimal set)
      - name: Install dependencies
        shell: pwsh
        run: |
          if (Test-Path windows-build-requirements.txt) {
            pip install -r windows-build-requirements.txt
          } elseif (Test-Path requirements.txt) {
            pip install -r requirements.txt
          } else {
            pip install streamlit pandas numpy
          }

      - name: Ensure PyInstaller
        run: pip install pyinstaller

      # PowerShell-friendly version probe (no Bash heredoc)
      - name: Show Streamlit version (sanity)
        run: python -c "import importlib.metadata as m; print('streamlit:', m.version('streamlit'))"

      # Build single-file EXE; bundle app.py next to the binary at runtime
      - name: Build (onefile)
        run: >
          pyinstaller --clean --onefile --noconsole
          --name EvidenceSynthesisApp
          --add-data "app.py;."
          --collect-all pandas
          --collect-all numpy
          --collect-metadata streamlit
          run_app.py

      - name: List dist
        run: dir dist

      # Smoke test: start EXE and probe home page
      - name: Smoke test EXE (serve and probe "/")
        shell: pwsh
        env:
          STREAMLIT_SERVER_HEADLESS: "true"
          STREAMLIT_SERVER_PORT: "8501"
          STREAMLIT_SERVER_ADDRESS: "127.0.0.1"
          STREAMLIT_BROWSER_GATHER_USAGE_STATS: "false"
        run: |
          $exe = Join-Path "dist" "EvidenceSynthesisApp.exe"
          Write-Host "Starting $exe ..."
          $p = Start-Process -FilePath $exe -PassThru
          try {
            $ok = $false
            for ($i=0; $i -lt 50; $i++) {
              try {
                $res = Invoke-WebRequest -UseBasicParsing -Uri "http://127.0.0.1:8501/" -TimeoutSec 3
                if ($res.StatusCode -in 200, 302, 403) { $ok = $true; break }
              } catch {
                Start-Sleep -Seconds 2
              }
            }
            if (-not $ok) {
              Write-Host "❌ App did not respond on http://127.0.0.1:8501/"
              throw "App not healthy"
            } else {
              Write-Host "✅ Streamlit responded."
            }
          } finally {
            if ($p -and -not $p.HasExited) { Stop-Process -Id $p.Id -Force }
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-windows-exe
          path: dist/EvidenceSynthesisApp.exe
          if-no-files-found: error
